### PR TITLE
Package Kubernetes v1.4.8 client binary

### PR DESCRIPTION
**Pull request by itskingori**
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v148.

Ps: This merges into `release-1.4` branch and if accepted, it will be tagged thereafter.

### CODE REVIEW

**Comment by itskingori** [comment]
We skipped 1.4.8. I'll create 1.4.9 after this goes in.

**Comment by adrianmoisey** [comment]
Why not branch `release-1.4` from the point that `1.4.7` got created?
It will result in a neater history

**Comment by itskingori** [comment]
> It will result in a neater history

I agree. Lemme work on that.

**Comment by adrianmoisey** [comment]
✨

**Comment by itskingori** [comment]
@adrianmoisey I've branched `release-1.4` from the point that `1.4.7` got created and rebased.

**Review by adrianmoisey — APPROVED** [review]

**Comment by adrianmoisey** [comment]
:+1:

**Pull request merged**
